### ISSUE TITLE
Add custom validations for inputs

### ISSUE THREAD

**Issue by xmnlab** [makim-org/makim#51]
Add an option for custom/extra validations for inputs.

for example:

```yaml
args:
   age:
     help: define the age
     type: integer
     validations:
       minimum: 0
       maximum: 150
```
