### ISSUE TITLE
Support option for environment activation

### ISSUE THREAD

**Issue by esloch** [makim-org/makim#52]
We need to add support for conda environment activation that will activate the environment beforehand before executing the environment.

for now, let's just support conda.

```
version: 1.0
env-file: .env
virtual-environment:
  application: conda
  name: my-env
groups:
  php:
    targets:
      print:
        help: print 1
        run: |
           print('1')
```

this option should be defined just in the global scope.
we need to investigate it later if we would like to have it for group and target scope as well. 

for now, we don't need to implement `source`, but it would be nice to have that, so it could create an environment in the case it doesn't exist.
